
- name: Redeploy coordinator1
  oozie_coordinator:
    state: present
    file: "{{ temppath.path }}/coordinator1.properties"
    url: "{{ knox_url }}"
    user: "{{ knox_user }}"
    password: "{{ knox_password }}"
    strict: "{{ knox_strict }}"